os: linux
dist: focal
language: ruby
rvm:
 - 2.7.3
jobs:
 include: 
 - name: “test” # existing functionality
   script: # existing functionality
    - ruby --version
 - name: “sbom”
   script: # existing functionality
     - cd ruby
     - bundle install
   addons:
     sbom:
       on:
         branch: 'main'
         pr: false
       # condition: false
       run_phase: "after_success" # 
       output_format: "spdx-json" # 
       output_dir: "/test" # 
       input_dir: "/ruby" #
